# Generated by Django 3.0.3 on 2020-07-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys_ICCN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionUtilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userpassword', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'gestion utilisateur',
                'ordering': ['id'],
            },
        ),
    ]
