# Generated by Django 3.0.3 on 2020-07-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys_ICCN', '0002_gestionutilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionutilisateur',
            old_name='ipaddress',
            new_name='ip_address',
        ),
    ]
